### ISSUE TITLE
Crash when logging in:

### ISSUE THREAD

**Issue by kazijehangir** [kazijehangir/BloodHub#6]
I registered a new account, verified the email through the link in the email (which is pretty cool), and then tried to log in as it showed the login screen after registration. 
It crashed with this error:
07-24 00:42:31.247 20134-20134/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.jexapps.bloodhub, PID: 20134
                                                   java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.jexapps.bloodhub.m_Model.User.account_type' on a null object reference
                                                       at com.jexapps.bloodhub.LoginActivity$7.onDataChange(LoginActivity.java:197)
                                                       at com.google.firebase.database.Query$1.onDataChange(Unknown Source)
                                                       at com.google.android.gms.internal.zzbmz.zza(Unknown Source)

**Comment by kazijehangir** [comment]
Fixed now.
