### ISSUE TITLE
Crash when opening app

### ISSUE THREAD

**Issue by kazijehangir** [kazijehangir/BloodHub#7]
07-24 00:47:08.505 20758-20758/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.jexapps.bloodhub, PID: 20758
                                                   java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.jexapps.bloodhub.m_Model.User.account_type' on a null object reference
                                                       at com.jexapps.bloodhub.SplashActivity$1.onDataChange(SplashActivity.java:36)
                                                       at com.google.firebase.database.Query$1.onDataChange(Unknown Source)
                                                       at com.google.android.gms.internal.zzbmz.zza(Unknown Source)

**Comment by kazijehangir** [comment]
Fixed by reinstalling
